# check-status.yml
---
  - hosts: webservers:loadbalancers
    become: true
    tasks:
      - name: check apache status
        command: service httpd status
        args:
          warn: no
        changed_when: false

      - name: this will not fail
        command: /bin/false
        ignore_errors: yes